export default {
  FETCH_ALL_POSTS: "FETCH_ALL_POSTS",
  FETCH_LOGIN_DETAILS: "FETCH_LOGIN_DETAILS",
  FETCH_BLOG_DETAILS: "FETCH_BLOG_DETAILS",
  UPLOAD_IMAGE: "UPLOAD_IMAGE",
  FETCH_TAGS: "FETCH_TAGS",
  REGISTER_USER: "REGISTER_USER",
};
